---
version: "2"
services:
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Minsk
    volumes:
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Configs/Emby:/config
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/TV:/data/tvshows
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Movies:/data/movies
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Photos:/data/photos
    ports:
      - 8096:8096
      - 8920:8920 #optional for secure connections
    restart: unless-stopped
    
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Minsk
    volumes:
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Configs/Jackett:/config
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
     
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=998 
      - PGID=100
      - TZ=Europe/Minsk
    volumes:
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Configs/Transmission:/config
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped  
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Minsk
    volumes:
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Configs/Sonarr:/config
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/TV:/tv
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Movies:/movies
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Minsk
    volumes:
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Configs/Radarr:/config
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Movies:/movies
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  
  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
       - PUID=998
      - PGID=100
      - TZ=Europe/Minsk
    volumes:
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Configs/Ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
  
## Home

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - DISABLE_JEMALLOC=true
      - PUID=998
      - PGID=100
      - TZ=Europe/Minsk
    volumes: 
      - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Configs/Homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
    restart: unless-stopped

## System Monitoring

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      environment:
        - PUID=998
        - PGID=100
        - TZ=Europe/Minsk
        - UMASK_SET=022
      volumes:
        - /srv/dev-disk-by-uuid-595b77af-d35a-4657-b1f5-aaf49c5bc4f4/Configs/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - 9292:9090
      restart: unless-stopped

  node-exporter:
      image: quay.io/prometheus/node-exporter:latest
      container_name: node-exporter
      network_mode: host
      environment:
        - PUID=998
        - PGID=100
        - TZ=Europe/Minsk
        - UMASK_SET=022
      volumes:
        - /:/host:ro,rslave
      ports:
        - 9100:9090
      restart: unless-stopped
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Minsk
      - UMASK_SET=022
    ports:
      - 3000:3000
    restart: unless-stopped
