global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.88.248:9292'] ## IP Address of the localhost
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.88.248:9100'] ## IP Address of the localhost
  
  - job_name: 'mikrotik'
    static_configs:
      - targets:
        - 192.168.88.1 # mikrotik_ip
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.88.248:9116  # The SNMP exporter's real hostname:port.
  - job_name: 'octoprint'
    static_configs:
      - targets: ['192.168.88.215:80']
    scrape_interval: 5s
    metrics_path: '/plugin/prometheus_exporter/metrics'
    params:
      apikey: ['__API_KEY__']
