---
version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - UMASK_SET=022
    ports:
      - "3000:3000"
    restart: unless-stopped
