---
version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Minsk
      - UMASK_SET=022
    ports:
      - 3000:3000
    restart: unless-stopped
