---
version: "3"
services:
  grafana:
    image: grafana/grafana:8.2.7
    container_name: grafana
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - ${VOLUME_PATH}/Configs/Grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
