---
version: "3"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - ${VOLUME_PATH}/Configs/Jackett:/config
      - ${VOLUME_PATH}/Torrents:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped
