version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=022
      - TZ=${TIME_ZONE}
    volumes:
      - ${VOLUME_PATH}/Configs/Jellyfin:/config
      - ${VOLUME_PATH}/TV:/data/tvshows
      - ${VOLUME_PATH}/Movies:/data/movies
      - ${VOLUME_PATH}/Photos:/data/photos
      - /etc/localtime:/etc/localtime:ro
    restart: "unless-stopped"
