---
version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - ${VOLUME_PATH}/Configs/Radarr:/config
      - ${VOLUME_PATH}/Movies:/movies
      - ${VOLUME_PATH}/Torrents:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7878:7878"
    restart: unless-stopped
