---
version: "3"
services:
  node-exporter:
    image: darkowl91/snmp_exporter_mikrotik # snmp exporter armv7 linux
    container_name: snmp-exporter
    ports:
      - "9116:9116"
    restart: unless-stopped
