---
version: "3"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - ${VOLUME_PATH}/Configs/Sonarr:/config
      - ${VOLUME_PATH}/TV:/tv
      - ${VOLUME_PATH}/Torrents:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8989:8989"
    restart: unless-stopped
